INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Et Magna Praesent LLP','felis, adipiscing fringilla, porttitor vulputate, posuere','',71);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Quis Foundation','pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim,','airport',93);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vitae Sodales Limited','Proin sed turpis nec mauris blandit mattis. Cras eget','department store, cafe',5);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Fusce Consulting','mollis nec,','college, tea room',67);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nibh Vulputate Mauris LLC','enim, sit amet ornare lectus justo eu arcu.','college',37);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Facilisis Vitae Corporation','Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non','wine shop, college',281);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Egestas Corporation','Mauris nulla. Integer urna.','',295);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Non Hendrerit Industries','nec tempus scelerisque, lorem ipsum sodales purus,','department store',326);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Penatibus Et Magnis Associates','arcu ac orci.','cafe',17);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Placerat Orci Company','Ut tincidunt orci quis lectus. Nullam suscipit, est','',500);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Auctor Quis Consulting','tellus, imperdiet non, vestibulum nec, euismod','',189);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Aliquam Ornare Foundation','eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed,','cafe, tea room',275);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Non Enim PC','enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit,','',204);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nullam Ut Nisi Ltd','feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper','',290);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Penatibus Et Corporation','sem semper erat, in','',44);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Rutrum Lorem Ac Industries','Fusce dolor quam, elementum at, egestas','wine shop, gallery',224);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Est Ac Mattis PC','rhoncus id, mollis nec, cursus a,','',482);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Facilisis LLP','metus sit amet','tea room, college',121);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sociis Natoque Foundation','lorem lorem, luctus ut, pellentesque eget, dictum','college',320);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sit Amet Consectetuer Company','magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu','',224);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Neque Venenatis Lacus Foundation','facilisis','college, airport',54);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ligula Consectetuer Inc.','dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum,','tea room',371);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Eget Foundation','mus. Proin vel arcu','gallery, wine shop',443);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Eget Mollis Lectus Foundation','faucibus.','',312);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Facilisis Inc.','convallis, ante lectus convallis est, vitae sodales nisi magna','school, tea room',232);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Pellentesque Habitant Industries','non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer,','gallery, department store',86);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Egestas Blandit Nam Associates','Morbi accumsan laoreet','school, college',434);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vel LLP','diam.','',291);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Risus Inc.','pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu','',17);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Placerat Associates','mauris, rhoncus id, mollis','',363);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Dolor Ltd','ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat','',41);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vivamus Non Lorem LLC','volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat','',500);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Aliquam Eros Limited','tellus non magna. Nam','college, school',495);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Justo Sit Corp.','lobortis. Class aptent taciti sociosqu ad litora torquent per','department store, gallery',402);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Aenean Limited','pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod','cafe, department store',49);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Laoreet Consulting','Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut,','airport, school',273);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Arcu Morbi Sit Consulting','tempus scelerisque, lorem ipsum sodales purus,','',288);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Rutrum Urna Institute','velit egestas lacinia.','cafe, wine shop',151);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Rhoncus Donec Est Foundation','semper,','cafe, college',9);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Erat Semper Rutrum Inc.','iaculis','college, department store',119);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vestibulum Lorem Limited','mauris ut mi. Duis risus odio, auctor','college',62);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Dignissim Industries','magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis,','cafe, tea room',437);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vestibulum Neque Sed PC','at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu','cafe, wine shop',380);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Cursus Et Inc.','tincidunt vehicula risus. Nulla','tea room, airport',338);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Metus Vitae Foundation','nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida','wine shop, college',208);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vulputate Ullamcorper Foundation','Quisque ac libero nec ligula','cafe, department store',493);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nec Urna Suscipit LLC','rutrum, justo.','tea room',110);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Non Lacinia At Foundation','quam quis','',134);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Odio Nam Interdum Corporation','dolor. Nulla semper tellus id nunc interdum feugiat. Sed','college',71);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('At Velit Pellentesque Foundation','Suspendisse','airport',450);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Amet Consectetuer Corporation','faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis','school',379);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Quis Pede Suspendisse Consulting','sodales nisi magna sed dui. Fusce aliquam, enim','school, gallery',447);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Pede Ac Consulting','ac libero nec ligula consectetuer rhoncus. Nullam velit dui,','',26);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Class Institute','mauris, rhoncus id, mollis nec, cursus a, enim.','gallery, cafe',234);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ipsum Ac Limited','molestie. Sed id risus quis diam','school, gallery',120);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Viverra LLP','ut, pharetra sed, hendrerit a, arcu. Sed et','',373);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ultrices Iaculis Odio Ltd','dictum eu, placerat eget, venenatis','cafe',149);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Felis Purus Industries','hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper,','',484);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Natoque Company','Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit','tea room',88);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sagittis Lobortis Mauris Ltd','ultrices sit amet,','',173);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Integer Urna Vivamus Institute','nunc. Quisque ornare tortor at risus. Nunc','wine shop',319);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Natoque Penatibus Et Consulting','Vivamus nisi.','tea room, school',392);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Facilisis Lorem Tristique Associates','lorem, luctus ut,','cafe',435);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mollis Phasellus Limited','nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae','school, college',388);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Lacus Quisque Incorporated','id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent','school',178);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Congue In Industries','leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis','',7);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Odio Tristique Pharetra Limited','interdum','wine shop',41);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nulla Eget PC','ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum.','cafe',89);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ante Vivamus Incorporated','erat. Etiam vestibulum massa rutrum magna. Cras convallis','',490);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Egestas Corp.','semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien.','gallery',270);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ante Lectus Foundation','Aliquam ultrices','wine shop, tea room',109);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Aliquam Ultrices Corp.','risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed','airport',400);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Consectetuer Rhoncus Inc.','purus','',85);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Massa Integer Company','Donec est. Nunc ullamcorper, velit','cafe, tea room',430);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Tristique Senectus Et Company','scelerisque neque. Nullam nisl.','',139);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Non Lacinia Consulting','molestie in, tempus','airport',354);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Molestie In Tempus Corporation','interdum feugiat. Sed nec metus facilisis lorem tristique aliquet.','',220);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Magna Consulting','ante. Nunc mauris','tea room, airport',301);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Interdum Curabitur PC','vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa.','',39);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nisi LLC','mattis','gallery, department store',87);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Non Corp.','Nulla tempor','airport, cafe',328);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Facilisis Magna Tellus Associates','Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla','department store, school',33);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Inceptos LLC','ut erat. Sed nunc est, mollis non, cursus non, egestas','airport',450);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Interdum Ligula Associates','Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim','airport, gallery',435);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Tellus Sem Incorporated','lectus pede','department store, college',131);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Massa Rutrum Limited','lobortis augue scelerisque mollis. Phasellus libero mauris,','airport, cafe',89);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mauris Ut Incorporated','sit amet, consectetuer','wine shop',169);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Consectetuer Euismod Ltd','mi eleifend egestas. Sed pharetra, felis eget varius','wine shop, airport',486);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Risus Varius Orci LLC','sollicitudin orci sem eget massa.','college, wine shop',449);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Eu Odio Tristique Associates','nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci.','',323);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ac Corporation','odio. Phasellus at augue id ante','tea room',210);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Et Netus Industries','facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet','airport, department store',225);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Magna Incorporated','rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus','school, department store',429);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Non Lobortis Quis Corporation','arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi.','cafe',39);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sit Amet Risus Foundation','interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non,','',224);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Pretium Corporation','odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec,','cafe',416);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Elit Pede Malesuada Consulting','blandit at,','',360);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Lorem LLP','lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum','cafe',132);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nec Luctus Felis Corporation','lorem ipsum sodales','school, gallery',176);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Proin Velit Sed Industries','Nulla eu neque pellentesque massa','wine shop',292);

INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Lorem Associates','metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare','',69);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Cursus Purus Incorporated','mauris ut mi. Duis risus odio, auctor vitae,','',366);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ac Metus Corporation','malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas,','college, airport',373);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Magna Nam Ligula Corp.','est. Nunc laoreet','gallery, school',367);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mollis Dui Incorporated','malesuada','school',474);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Dui Nec Limited','iaculis aliquet diam. Sed','airport',307);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sapien Cursus In Corp.','gravida molestie arcu. Sed eu nibh vulputate','tea room',448);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mus Donec Institute','risus. Duis a mi fringilla mi lacinia mattis. Integer eu','cafe, school',162);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Cursus Industries','urna suscipit nonummy. Fusce fermentum fermentum arcu.','wine shop, tea room',44);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nec Company','diam. Pellentesque habitant morbi tristique senectus et netus','airport, wine shop',138);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Aliquam Institute','eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in','',13);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Posuere Inc.','pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla','cafe',290);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Est Tempor Ltd','sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin','gallery, department store',203);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Tellus Nunc Lectus Incorporated','non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam','cafe',86);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ipsum Associates','Duis mi','',19);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vestibulum Consulting','nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque','',430);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Erat Consulting','tellus sem mollis dui, in sodales elit','college, cafe',124);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Leo Cras Vehicula Institute','dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis','college, cafe',444);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Id Blandit Company','turpis non enim. Mauris quis turpis vitae purus gravida sagittis.','wine shop, gallery',463);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nulla Semper LLC','Suspendisse','',195);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Egestas Corp.','risus odio, auctor vitae, aliquet nec, imperdiet nec, leo.','',426);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Velit Dui Semper LLP','pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris,','',476);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Posuere At LLC','Nunc laoreet lectus quis','',351);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Malesuada Vel Associates','dolor','college',122);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Leo Vivamus Nibh Industries','nunc. Quisque ornare tortor at','tea room, college',88);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Orci Consectetuer Euismod Institute','Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim','wine shop, college',270);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sit Corporation','id ante dictum cursus. Nunc mauris elit,','',31);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Natoque Penatibus Et LLC','Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat','',51);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ipsum Dolor Sit Corporation','a felis','',80);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ullamcorper Eu Institute','purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue','tea room, school',366);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Proin Dolor Industries','placerat, augue. Sed molestie. Sed id risus quis diam','tea room',144);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Tellus Suspendisse Limited','Ut sagittis lobortis mauris. Suspendisse aliquet molestie','cafe',96);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vivamus Sit Corporation','magnis dis parturient montes, nascetur ridiculus','department store',187);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('A Incorporated','metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis','tea room',169);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Eu LLC','Morbi','gallery',94);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Neque Et Nunc LLP','lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi','',423);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Non Consulting','mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam','airport, tea room',463);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Consectetuer Consulting','nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque','wine shop, school',259);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vestibulum Mauris Magna Consulting','magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus','school, tea room',54);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Blandit Congue Company','non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin','',106);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Phasellus Elit Pede Industries','rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem,','tea room',3);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vitae Mauris Sit LLC','Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam','wine shop, college',148);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Suspendisse Sagittis Foundation','imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum','tea room',427);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ligula Corporation','Donec at arcu. Vestibulum','college',103);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nec Tempus Ltd','egestas, urna justo','school, gallery',306);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nullam Scelerisque Neque Foundation','id sapien. Cras dolor','',43);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Risus Ltd','at, iaculis quis, pede. Praesent eu dui. Cum sociis','gallery, cafe',205);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Feugiat LLP','rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed','tea room',384);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Tristique Ltd','nulla. Donec non justo. Proin non massa non ante','cafe, airport',187);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Luctus Vulputate Ltd','Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam','department store',347);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('In Hendrerit Consulting','tellus','',175);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Dictum LLC','parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio','gallery',27);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Hendrerit A Industries','Cum sociis natoque penatibus et magnis dis parturient','',392);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Litora Torquent Ltd','amet, consectetuer adipiscing elit.','gallery, department store',7);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Amet Ante Corporation','enim, sit amet ornare lectus justo','college',255);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Massa LLP','amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque','cafe, tea room',319);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mauris Nulla PC','in, cursus et, eros.','tea room, cafe',422);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Urna Nunc Consulting','ridiculus mus. Donec dignissim magna a tortor. Nunc commodo','',10);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mi Company','orci lobortis augue scelerisque mollis. Phasellus libero','tea room',206);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Purus Ac Tellus Corporation','eget metus eu erat semper rutrum.','',472);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('In Dolor Fusce Incorporated','Proin','wine shop, school',421);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Fringilla Euismod PC','Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit','department store, college',303);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Turpis Industries','vestibulum nec, euismod in, dolor. Fusce','',164);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Malesuada Ltd','faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa','college, wine shop',308);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sed Tortor Incorporated','ac orci.','tea room, gallery',384);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Quisque Tincidunt Pede Company','fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy','tea room',148);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Rutrum Justo LLC','In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas.','',276);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sodales Inc.','libero. Proin sed turpis nec mauris blandit mattis. Cras','tea room',129);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sit Amet Company','enim mi tempor lorem, eget','',154);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Dolor Foundation','nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam','college, tea room',159);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Odio Industries','mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et,','gallery',159);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nullam Enim Sed Inc.','rutrum non, hendrerit id, ante. Nunc mauris','college',325);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vitae Orci Phasellus Corporation','egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna,','',490);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Orci Ut Sagittis Inc.','tempor bibendum. Donec felis orci, adipiscing non,','',275);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Convallis Ltd','at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis','gallery, college',33);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mattis Velit Justo LLP','Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis','',329);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Faucibus LLP','lorem lorem, luctus ut,','department store, wine shop',121);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mi PC','libero at auctor','cafe',364);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Elit Elit Fermentum Institute','semper erat, in','',178);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sed Consulting','non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non','wine shop, tea room',233);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Posuere At LLP','in, hendrerit consectetuer, cursus et, magna. Praesent','college, school',125);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Cursus Non Egestas LLC','arcu. Vestibulum ante ipsum','department store, wine shop',229);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('A Arcu Sed Institute','Lorem','college, tea room',491);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vestibulum Ante LLC','rutrum lorem ac','',442);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ut PC','vitae nibh. Donec est mauris, rhoncus id, mollis','airport',324);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nunc Quis LLC','eros non enim commodo hendrerit. Donec','department store',316);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Dictum Associates','luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat','',248);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Metus LLC','libero dui nec','airport',40);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vel Turpis Aliquam Inc.','nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus','',314);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ultrices Vivamus Rhoncus Foundation','sagittis. Nullam vitae diam. Proin dolor. Nulla semper','',447);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Est Nunc Consulting','nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare','',215);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nulla Institute','tincidunt nibh.','',429);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vestibulum Mauris Magna Foundation','in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis','tea room',498);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Aliquam Vulputate Ullamcorper PC','mus. Donec dignissim magna a tortor. Nunc commodo','gallery',36);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Accumsan Convallis Ante Corp.','sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam','gallery, wine shop',484);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Lorem Consulting','tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia','',185);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ligula Corp.','arcu et pede. Nunc sed orci lobortis','department store, school',186);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sed Turpis Limited','diam. Sed','',409);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Inceptos Consulting','Vivamus nisi. Mauris','tea room, gallery',22);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nullam Corp.','nostra, per inceptos hymenaeos. Mauris ut quam vel','gallery',115);

INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sed Dui Fusce PC','parturient montes, nascetur ridiculus mus.','gallery',274);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sapien Cursus In Incorporated','nulla. In tincidunt congue turpis. In condimentum. Donec at','department store',144);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Leo Elementum Corp.','mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet','',113);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Quisque Nonummy Incorporated','Nulla aliquet. Proin velit. Sed','airport',62);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Imperdiet Inc.','massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut','airport, school',280);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mauris A Institute','sodales. Mauris blandit enim consequat purus. Maecenas libero','',231);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Orci Phasellus Dapibus LLC','ut ipsum ac mi eleifend egestas. Sed pharetra, felis','',208);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Eget Metus Ltd','sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis','cafe, wine shop',462);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ullamcorper Velit LLC','nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing','wine shop',474);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Non Company','dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus','',149);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Integer Sem Foundation','magna. Lorem ipsum dolor','wine shop, school',177);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mauris Industries','blandit. Nam nulla magna, malesuada vel, convallis in,','department store, airport',401);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Varius Ultrices Industries','at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa','school',239);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Vitae Company','Phasellus elit pede, malesuada','',429);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nunc Associates','pede.','gallery',277);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Posuere Enim Ltd','ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut','cafe, gallery',47);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ornare Industries','Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc','wine shop',160);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Eleifend Cras Inc.','orci luctus et ultrices posuere cubilia Curae; Phasellus','',375);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Parturient Associates','sem. Pellentesque ut ipsum','',401);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Phasellus Elit LLC','a neque. Nullam ut','gallery',498);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mattis Velit Justo Foundation','malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut','tea room, wine shop',368);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Elit Associates','mi. Aliquam gravida mauris ut mi. Duis','',301);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Quisque Consulting','magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum','tea room',431);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ac Limited','morbi tristique','',292);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Tortor Nibh Sit Foundation','id nunc interdum feugiat. Sed nec metus','',286);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ipsum Company','Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus','',99);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Aliquet Company','faucibus ut, nulla. Cras eu tellus eu','cafe, school',127);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nullam Nisl Maecenas Ltd','lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet','school',361);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Lectus Company','Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum','department store',124);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('In Cursus Limited','Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus','college',436);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Donec Limited','In nec orci. Donec nibh. Quisque nonummy ipsum','gallery, cafe',386);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mollis Lectus Pede Associates','ut, sem. Nulla interdum. Curabitur dictum. Phasellus in','',22);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Tempor Erat Limited','Vivamus sit amet risus.','',250);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Duis Sit LLC','scelerisque neque. Nullam nisl.','airport',449);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Et Magnis Associates','Mauris eu turpis.','department store, wine shop',289);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ultricies Adipiscing Enim Associates','purus,','wine shop',470);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Id Magna Et LLC','Aliquam ultrices iaculis odio. Nam interdum','',287);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Etiam Inc.','sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi.','',339);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nunc Laoreet Lectus PC','at pretium aliquet, metus urna convallis erat,','',193);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Eu Elit Corp.','magna. Cras convallis convallis','gallery, department store',143);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sed Dui Ltd','ac urna. Ut tincidunt vehicula risus.','cafe',59);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ultrices Posuere Corporation','lobortis ultrices. Vivamus rhoncus. Donec est.','department store',185);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Commodo Auctor Velit Consulting','Ut tincidunt vehicula risus.','airport',2);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Odio Nam LLC','orci. Donec nibh. Quisque nonummy ipsum','',485);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Lectus Quis Foundation','tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis','school, airport',394);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Dui Foundation','egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris','airport',99);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Proin Nisl Ltd','ultrices,','college, wine shop',228);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Phasellus Dolor Elit Incorporated','at risus. Nunc ac sem ut dolor dapibus gravida.','tea room, cafe',70);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mus Aenean Eget Associates','massa. Mauris vestibulum, neque sed','college, airport',116);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mi Lacinia Mattis LLP','mauris. Suspendisse aliquet molestie tellus. Aenean egestas','cafe, wine shop',497);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Quam Vel Sapien Ltd','aliquet. Proin velit. Sed malesuada augue ut','',334);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Egestas Lacinia Inc.','elit erat vitae risus. Duis a mi fringilla','cafe, college',260);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Faucibus Consulting','scelerisque','college, wine shop',379);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Magnis Dis Inc.','pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero','',369);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Aenean Institute','eu, odio.','tea room, school',148);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sem Ut Dolor Consulting','facilisis lorem tristique aliquet. Phasellus','school, cafe',356);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Non Massa Non Consulting','nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu.','school',212);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Metus Institute','ut odio vel est tempor bibendum. Donec felis orci,','tea room, wine shop',159);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Aliquet Sem Ut Foundation','tempus scelerisque, lorem ipsum sodales purus,','',13);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Purus Industries','urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas','department store, cafe',114);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Phasellus Fermentum Limited','ultricies dignissim lacus. Aliquam rutrum','school, wine shop',282);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Consequat Auctor Nunc Foundation','nostra, per inceptos','airport',362);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Tristique Institute','enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac','airport, gallery',184);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Amet PC','Fusce dolor','',368);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Purus In Molestie Corporation','leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis','',187);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Eleifend Egestas Sed Ltd','vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc','school',185);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Suscipit Incorporated','iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus','cafe',498);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Etiam Imperdiet Dictum Inc.','nonummy ipsum','',281);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Eu Corp.','eros. Nam consequat dolor','school',482);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Auctor Velit Eget Incorporated','mattis ornare, lectus ante dictum mi, ac mattis velit justo','airport',334);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ut Industries','magna tellus faucibus leo, in lobortis tellus','',199);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ante Iaculis Associates','Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur','college',494);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Iaculis PC','in faucibus','',75);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Est Congue PC','Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla','tea room',423);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Quis Corporation','magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna.','',448);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Eu Ultrices Sit Associates','lacus. Quisque purus sapien, gravida non, sollicitudin a,','cafe',196);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Proin LLC','quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus','',314);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Lacus Etiam Bibendum LLP','ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu.','',6);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Dictum Sapien Ltd','nibh sit amet orci. Ut sagittis lobortis mauris.','',433);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nibh Phasellus Company','sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel,','gallery, department store',156);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Et Company','luctus felis purus ac tellus. Suspendisse sed dolor. Fusce','airport',420);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Congue Turpis In Corp.','tempor arcu. Vestibulum ut','',158);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Non Massa Consulting','Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin','school, wine shop',334);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Accumsan Convallis Ante Foundation','luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris','cafe, college',377);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Aliquam Vulputate LLC','penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna','',134);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Neque Consulting','Maecenas libero est, congue a, aliquet vel, vulputate','',63);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nunc Ullamcorper Velit Consulting','luctus felis purus ac tellus. Suspendisse','tea room, college',212);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Integer Industries','a, scelerisque sed, sapien. Nunc pulvinar','college',93);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Enim Non Inc.','ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit','gallery, wine shop',299);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Ipsum Inc.','eu dolor egestas rhoncus. Proin nisl sem,','department store, cafe',491);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Purus Ac Tellus Corp.','semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede,','',284);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Suspendisse Limited','augue ac ipsum. Phasellus vitae mauris sit amet lorem','school, wine shop',394);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Mauris Sagittis Limited','nec, cursus a, enim. Suspendisse aliquet,','school',319);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Sem Molestie Sodales Foundation','interdum. Sed auctor odio a purus. Duis elementum, dui quis','',210);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Porta Foundation','laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend,','school, cafe',137);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Lobortis Tellus Corporation','mauris a nunc. In at pede. Cras vulputate','',29);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Eu Corporation','ullamcorper, nisl','',160);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('In Faucibus Orci Inc.','quam. Pellentesque','tea room',411);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('Nonummy Inc.','pulvinar arcu et pede. Nunc sed orci lobortis','cafe, wine shop',249);
INSERT INTO Lokalita (nazev,popis,typ,adresaID) VALUES ('A Facilisis Non Consulting','Mauris','department store, school',418);

