INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (358,295,'Duis Dignissim Tempor Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (134,42,'Nisl LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (64,56,'Maecenas Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (24,235,'Duis Gravida Praesent LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (321,263,'Dui Nec Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (160,33,'Duis Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (257,51,'Commodo Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (109,139,'Vel LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (178,143,'Pede Cum Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (275,242,'Metus Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (164,285,'Fusce Fermentum Fermentum Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (7,21,'Odio Vel Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (305,267,'Cum Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (175,106,'Diam LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (349,28,'Natoque Penatibus Et Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (361,27,'Sed Est Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (28,240,'Semper Nam Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (202,76,'Ante Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (190,102,'Scelerisque Mollis Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (201,31,'Mattis Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (357,92,'At Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (12,285,'Urna Vivamus Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (107,153,'Integer Urna Vivamus LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (277,268,'Cras Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (354,217,'Nam Consequat Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (261,54,'Cum Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (221,223,'Metus Vitae Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (188,9,'Orci Quis Lectus Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (318,30,'Placerat Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (256,268,'Quis Diam Luctus Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (276,102,'Magna A Neque LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (326,33,'Tempor Bibendum Donec Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (64,39,'Posuere Enim Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (351,12,'Enim Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (197,18,'Dictum Proin Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (299,14,'Non Leo Vivamus Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (159,205,'Lobortis Nisi Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (98,27,'Sed Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (299,64,'Pede Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (199,210,'Varius Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (268,11,'Quis Tristique Ac Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (166,238,'Et Tristique Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (129,262,'Ac Fermentum Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (105,54,'In LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (86,199,'Nonummy Ut Molestie Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (245,157,'A Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (74,62,'Et Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (74,36,'Donec At Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (370,289,'Tortor Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (4,181,'Feugiat Tellus Lorem Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (201,14,'Sagittis Semper Nam Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (181,130,'Sed Pede Cum Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (331,275,'A Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (52,24,'Venenatis Vel Faucibus Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (358,72,'Elit Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (214,69,'Vulputate Posuere Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (38,97,'Accumsan Sed Facilisis LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (162,42,'In Sodales Elit Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (251,282,'Ultricies Ligula Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (45,233,'Mauris Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (290,10,'Tristique Senectus Et Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (152,1,'Donec Dignissim Magna Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (283,125,'Velit Sed Malesuada PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (58,161,'Donec Egestas Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (291,221,'Auctor Nunc Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (138,53,'Fringilla Euismod Enim Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (187,36,'Eu Eleifend Nec Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (203,89,'At Libero PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (38,99,'Donec At Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (259,230,'Sit Amet Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (132,21,'Nisi Nibh Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (81,205,'Libero At Auctor Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (353,180,'Non Hendrerit Id Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (210,64,'Tincidunt Aliquam Arcu Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (280,75,'Dui Nec Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (272,200,'Dictum Proin Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (317,164,'Nunc Nulla Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (351,249,'Elementum Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (147,166,'Luctus Sit Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (140,290,'Donec Egestas Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (279,119,'Ridiculus Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (344,214,'Sed Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (36,298,'Adipiscing Mauris Molestie Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (59,138,'Erat Volutpat Nulla Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (34,203,'Dis Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (41,272,'Nec Ligula Consectetuer Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (147,103,'Pede Nec Ante Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (327,191,'Lectus Quis Massa Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (369,156,'Ipsum Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (305,33,'Tellus Non Magna Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (245,84,'Dolor Vitae Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (275,16,'Accumsan Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (308,61,'Massa Lobortis Ultrices Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (275,237,'Aliquam Fringilla LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (194,48,'Proin PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (101,204,'Dui Semper Et Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (41,94,'Ante Dictum Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (243,160,'Augue Ac Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (318,277,'Adipiscing Enim Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (232,132,'Interdum Feugiat Consulting');

INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (281,83,'Tristique Senectus Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (261,65,'Ante Maecenas Mi Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (301,218,'Pharetra Felis Eget LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (30,160,'Integer Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (262,33,'Quam Curabitur Vel Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (242,165,'Semper Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (385,120,'In Lorem Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (101,11,'Ligula LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (79,57,'Mi Tempor Lorem LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (395,52,'Elit Etiam Laoreet Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (306,264,'Gravida Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (312,239,'Nisl Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (395,53,'Euismod Urna Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (141,89,'Eu Augue Porttitor LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (80,110,'Sed Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (163,81,'Natoque Penatibus Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (32,179,'Ipsum Porta Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (369,293,'Aenean Eget Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (51,142,'Mauris Ut Mi Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (22,39,'Velit Quisque Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (155,124,'Proin Mi Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (397,84,'Vestibulum Ante Ipsum Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (179,143,'Consectetuer Ipsum Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (86,265,'Libero PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (320,220,'Sed Diam Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (395,260,'Amet Lorem Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (133,169,'Elit Pharetra LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (126,259,'Sagittis Duis Gravida Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (26,58,'Nam Nulla Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (13,77,'Arcu Vestibulum Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (277,148,'Duis Volutpat Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (224,293,'Ipsum Nunc Id LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (323,41,'Diam Eu Dolor Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (233,67,'Risus In Mi LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (53,100,'Ipsum Curabitur Consequat PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (40,83,'Lectus Quis Massa LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (71,81,'Neque Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (11,11,'Mattis Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (192,41,'Tortor Nunc Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (385,235,'Nisl Maecenas Malesuada LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (200,189,'Convallis Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (173,166,'Morbi Vehicula LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (13,30,'Mauris A Nunc LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (290,195,'Sollicitudin Orci Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (49,17,'Ut Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (122,279,'Ac Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (287,37,'Mauris Vestibulum Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (237,59,'Egestas Hendrerit Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (224,284,'Egestas Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (31,150,'Proin Vel Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (90,146,'Tellus Imperdiet Non Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (300,202,'Cum Sociis Natoque Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (59,1,'Fames Ac Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (168,265,'Interdum Ligula Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (221,88,'Nulla In Tincidunt PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (102,229,'Tellus Aenean Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (200,69,'Eu Eleifend PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (389,288,'Nunc Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (263,259,'Et Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (20,151,'Nulla Tincidunt Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (359,74,'Sed Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (270,31,'Erat Vitae Risus Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (150,290,'Imperdiet Ornare In PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (139,183,'Molestie Tellus Aenean LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (114,38,'Mauris Eu Elit Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (232,265,'Pellentesque Habitant Morbi LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (165,152,'Fringilla LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (239,140,'Blandit Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (133,296,'Vulputate Eu Odio Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (148,110,'Eu Sem Pellentesque Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (73,293,'Donec At Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (139,138,'Molestie Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (188,145,'Sagittis Duis Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (390,255,'Proin Sed Turpis Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (129,235,'Volutpat Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (50,299,'Pharetra Nibh Aliquam Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (13,105,'Adipiscing Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (285,65,'Sit Amet Dapibus Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (365,283,'Mus Proin Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (392,132,'Aenean Massa Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (290,216,'Egestas Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (250,108,'Odio Sagittis Semper Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (273,177,'Lacinia Orci Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (376,191,'Donec LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (374,298,'Donec Nibh Quisque Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (74,220,'Fusce Diam Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (70,43,'Cubilia Curae; Donec Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (259,186,'Fusce Mi Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (177,201,'Vitae Aliquam Eros Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (352,161,'Odio Vel Est LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (376,139,'Donec Fringilla Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (398,283,'Id Risus Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (248,264,'Pharetra Nam PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (154,81,'Velit Aliquam Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (43,149,'Et Libero Proin Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (44,162,'Rutrum Lorem PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (46,47,'Pellentesque Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (159,230,'Dui Nec Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (164,65,'Duis Risus Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (296,175,'Justo Industries');

INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (104,28,'Cursus Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (181,157,'A Enim Suspendisse PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (156,138,'Sed Leo Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (239,19,'Sed Orci Lobortis Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (186,86,'Eleifend Cras Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (14,153,'Vitae Dolor Donec Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (344,16,'Rhoncus Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (382,268,'Orci Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (3,179,'Vitae Odio Sagittis Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (47,25,'Dictum Sapien LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (31,211,'Fringilla Ornare Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (245,261,'Dolor Dolor Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (251,6,'Morbi Quis Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (369,258,'Ligula Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (398,34,'Pellentesque Habitant Morbi Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (180,5,'Ante Vivamus Non Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (98,268,'Ante LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (300,145,'Libero Integer In Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (187,287,'Adipiscing Elit Curabitur PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (400,25,'Nascetur LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (9,163,'Tincidunt Orci Quis LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (81,26,'Amet Lorem LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (272,147,'Metus Urna Convallis PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (39,39,'Molestie Orci Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (342,162,'A Ultricies Adipiscing PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (135,145,'Donec Elementum Lorem Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (34,143,'Nunc Quisque PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (92,3,'Purus Ac PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (342,69,'Sed Dictum Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (256,295,'Integer In Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (70,8,'Amet Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (269,60,'Natoque Penatibus Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (294,264,'Urna Convallis LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (397,179,'Lectus PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (22,141,'Donec Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (346,269,'Imperdiet Non LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (18,17,'Suspendisse Non Leo Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (120,6,'Egestas PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (216,159,'Semper Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (316,26,'Ante Vivamus Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (8,61,'Aenean Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (234,235,'Nunc Mauris Morbi Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (303,194,'Nec Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (66,118,'Tempor Erat Neque Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (128,275,'Eleifend Egestas Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (182,212,'Nisi Mauris Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (15,28,'Vel Vulputate Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (4,214,'Dolor Donec Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (235,57,'Proin Ultrices Duis Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (132,156,'Orci Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (230,24,'Ante Nunc Mauris Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (396,77,'Aliquam Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (264,55,'Nam Nulla Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (289,275,'Purus Sapien Gravida Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (319,40,'Risus Duis A Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (75,159,'Nibh LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (189,190,'Fermentum Vel Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (18,249,'Mauris Eu Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (29,281,'In Consequat Enim Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (327,230,'Curabitur Vel Lectus Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (201,48,'Parturient Montes Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (184,89,'Aliquam Nisl Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (31,67,'Tellus Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (43,59,'Congue A Aliquet PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (66,105,'Erat Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (209,66,'Sed Consequat Auctor Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (255,232,'Feugiat Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (147,193,'Ipsum Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (340,51,'Gravida Non Sollicitudin Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (214,158,'Donec Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (287,238,'Nulla Dignissim Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (84,179,'Venenatis PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (298,168,'Augue Sed Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (223,139,'Enim Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (43,41,'Convallis Ante Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (53,89,'Dolor Sit Amet Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (131,41,'Ac Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (295,37,'Pede Nunc Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (248,253,'Lacinia Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (43,206,'Est Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (92,106,'Class Aptent LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (260,296,'Donec Elementum Lorem Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (198,174,'Tempus Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (6,99,'Sit Amet Ornare PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (294,72,'Dui Lectus Rutrum Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (139,115,'Commodo Ipsum Suspendisse Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (196,49,'Bibendum Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (217,53,'Gravida Aliquam Tincidunt Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (47,157,'Tristique Aliquet Phasellus LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (334,256,'Orci Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (286,95,'Sed Diam Lorem LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (19,158,'Malesuada Vel Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (354,222,'Tellus Nunc Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (238,210,'Vestibulum Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (306,22,'Aliquam Nisl Nulla Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (5,257,'Metus In Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (258,166,'Enim Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (216,254,'Non Egestas A PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (31,218,'Lorem Ut Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (330,72,'Pharetra Quisque Institute');

INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (196,133,'Semper Egestas Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (322,100,'Felis Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (210,278,'Ante Ipsum Primis Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (133,243,'Ante Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (96,202,'Tempor Augue Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (177,57,'Ante Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (76,58,'Massa Lobortis Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (315,24,'Facilisis Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (118,51,'Nunc Mauris Elit LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (109,207,'Mauris Integer Sem Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (229,224,'Pellentesque Massa Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (267,263,'Congue In Scelerisque Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (343,115,'Orci Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (361,142,'Diam Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (73,166,'Enim Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (13,260,'Et LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (144,131,'Nam Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (25,140,'Facilisis Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (3,89,'Fusce PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (131,297,'Dui Lectus Rutrum LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (275,118,'Mi Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (319,228,'Nisl Arcu Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (188,184,'Lacus Ut Nec Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (66,33,'In Felis Nulla Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (211,219,'Non Lobortis Quis Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (246,62,'Fusce Dolor Quam Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (372,203,'Magna Nec Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (85,145,'Risus Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (231,177,'Auctor Nunc Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (52,171,'Proin Non Massa LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (59,228,'Dignissim Lacus Aliquam LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (373,262,'Eu Arcu Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (182,151,'Cursus PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (235,87,'Penatibus Et Magnis LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (38,271,'Donec Nibh Enim LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (116,172,'Dictum Mi Ac Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (260,227,'Vitae Aliquet Nec Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (286,188,'Lobortis Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (191,71,'Nam Porttitor Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (294,250,'Mus Aenean LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (206,194,'Risus Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (181,39,'Lectus Convallis Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (400,20,'Risus Donec Egestas Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (270,61,'In Aliquet Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (98,66,'Mauris Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (122,3,'Aliquam Adipiscing PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (5,91,'Malesuada Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (181,136,'Ac Mattis PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (344,210,'Mauris Blandit Mattis PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (330,72,'Erat Etiam Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (15,197,'Interdum Nunc Sollicitudin PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (74,294,'Mauris Magna Duis Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (338,235,'Sollicitudin Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (27,274,'Convallis Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (63,139,'Vel Venenatis Vel Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (238,10,'Est Ac Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (30,186,'Nulla Integer Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (313,281,'Duis Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (246,197,'Ac Turpis Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (368,14,'Tincidunt Nibh Phasellus PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (191,143,'Eget Varius Ultrices LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (226,237,'Nulla Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (277,65,'Sagittis Nullam Vitae Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (293,151,'A Aliquet Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (71,275,'Et LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (377,277,'Non Egestas A Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (130,274,'Iaculis Enim Sit Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (320,32,'Mauris Blandit Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (288,75,'Cursus A Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (174,87,'Nunc LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (57,298,'Feugiat Nec Diam Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (400,171,'Duis Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (392,49,'Eget Varius Ultrices Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (204,153,'Tempor Lorem Eget Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (167,156,'Sociis Natoque Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (178,5,'Proin Mi Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (147,18,'Nec Diam Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (263,253,'A Purus Duis Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (261,257,'Arcu Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (112,238,'Auctor Odio A Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (374,115,'Tellus Aenean Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (230,31,'Vulputate Lacus Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (27,62,'In Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (356,164,'Consequat Auctor Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (281,157,'Id Nunc Interdum PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (290,65,'Gravida Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (275,105,'Aliquam Arcu Aliquam Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (275,116,'Mattis PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (175,299,'Pede Cum Sociis Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (122,166,'Aliquam Auctor Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (96,220,'Nam Tempor Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (221,39,'Nisi Cum Sociis Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (118,38,'Magna Tellus Faucibus Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (139,268,'Eget Volutpat Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (44,30,'Odio Etiam Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (387,224,'Suspendisse Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (200,101,'Augue Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (303,110,'Placerat Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (249,271,'Id PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (179,133,'Convallis Est Vitae LLC');

INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (322,96,'Imperdiet Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (19,54,'Nullam Nisl LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (350,39,'Mauris Morbi Non LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (120,237,'Risus Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (307,125,'Nam Tempor Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (231,154,'Ut Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (387,168,'Orci Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (354,198,'Cum Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (121,173,'Lobortis Ultrices Vivamus Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (198,235,'Ut Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (4,134,'Orci Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (30,217,'Gravida Praesent Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (48,74,'Lacinia Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (200,24,'Euismod Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (198,99,'Arcu Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (68,3,'Quis PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (369,82,'Ligula Elit Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (189,89,'Tincidunt Pede Ac Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (223,117,'Ullamcorper Magna Sed LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (343,18,'Egestas Nunc Sed Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (134,235,'Eget Massa Suspendisse Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (288,257,'Facilisis Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (264,170,'Id Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (206,179,'Ornare Lectus Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (20,78,'Urna Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (372,233,'Mi PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (251,161,'Eu Odio Tristique Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (314,250,'Nec Tempus Scelerisque Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (207,220,'Eleifend Egestas Sed Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (183,81,'Eget Nisi Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (397,206,'Urna Vivamus Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (315,263,'Urna LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (6,214,'Non Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (203,17,'Lorem Ipsum Dolor Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (59,37,'Ac Fermentum Vel Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (64,173,'Quam Quis Diam Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (212,282,'Sed Nunc Est Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (75,106,'Ullamcorper Duis Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (13,49,'Mus Proin Vel Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (243,168,'Sit Amet LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (184,127,'Quam LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (14,156,'Nisl Sem Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (350,196,'Non Feugiat Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (357,246,'Enim Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (359,159,'Elit Aliquam Auctor Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (70,144,'Quisque Varius Nam Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (250,192,'Erat Sed Nunc Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (223,296,'Donec Fringilla Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (61,238,'Mauris Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (26,164,'Quisque LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (125,118,'Fusce Mollis Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (235,112,'Cum Sociis Natoque Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (33,14,'Erat Vitae Risus Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (328,30,'Lacus Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (238,76,'Arcu Morbi Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (349,57,'Congue In Scelerisque Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (299,54,'Litora Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (97,28,'Ac Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (43,21,'Nunc Pulvinar Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (290,293,'Nunc Ullamcorper Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (120,155,'Dapibus LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (284,241,'At Pretium Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (14,143,'Adipiscing LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (75,107,'Orci Luctus Et Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (252,214,'Lectus Ante Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (132,45,'Mi Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (35,279,'Odio Aliquam Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (361,265,'Ligula Aenean LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (226,183,'Sed Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (140,230,'Dui Semper Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (73,220,'Interdum Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (262,128,'Placerat Orci Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (340,90,'Feugiat LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (297,30,'Ipsum Curabitur Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (320,237,'Nunc Ut Erat Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (126,289,'Luctus PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (35,169,'Mattis Velit Justo LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (60,85,'Tempus Lorem Fringilla PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (273,247,'Dui Suspendisse Ac Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (271,5,'Sociis Natoque Penatibus Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (57,233,'Quam Dignissim Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (132,152,'Sed Nunc Est Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (118,121,'Tristique Neque Venenatis PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (378,214,'Libero Dui Nec Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (318,202,'Purus Nullam Scelerisque LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (369,295,'Nonummy Ut Molestie Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (10,261,'Interdum Libero Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (195,172,'Enim Diam Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (381,168,'Ipsum Curabitur Consequat Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (262,2,'Pede Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (94,2,'Consectetuer Euismod Est LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (275,101,'Maecenas Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (303,222,'Elit Pretium Et Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (361,285,'Diam Nunc Ullamcorper Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (43,114,'Magnis Dis Parturient PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (243,123,'Ultricies Adipiscing Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (157,11,'Ligula Consectetuer Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (149,187,'Diam Pellentesque Habitant Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (100,25,'Neque Sed Sem Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (110,105,'Tincidunt Adipiscing Mauris Industries');

INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (297,93,'Malesuada PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (141,11,'Ipsum Non Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (310,63,'Diam At Pretium Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (110,128,'Dui In PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (366,213,'Eu Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (377,300,'Dui Lectus Rutrum Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (217,288,'In Magna Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (248,254,'Urna Nullam Lobortis Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (372,49,'Nullam Vitae LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (4,109,'Quisque Porttitor LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (288,195,'Curabitur Massa Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (269,297,'Mauris Morbi Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (361,186,'Magna Malesuada Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (345,76,'Aliquam Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (118,18,'Lorem Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (277,169,'Orci Sem Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (231,289,'Sociis Natoque Penatibus Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (17,57,'Magna Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (245,291,'Eget Tincidunt LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (77,136,'Amet Orci Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (369,277,'Sed Pede Cum LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (295,299,'Sapien Nunc LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (24,277,'Mattis Cras Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (109,22,'Quis Urna Nunc Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (316,128,'Facilisi Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (367,253,'Est Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (343,69,'Nibh Aliquam Ornare Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (193,38,'Adipiscing Lobortis Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (346,183,'Morbi Quis Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (184,299,'Elit Nulla LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (234,246,'Dictum Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (309,199,'Sociis Natoque LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (374,238,'Semper Rutrum Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (106,93,'Etiam Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (232,208,'Nisl Maecenas Malesuada Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (13,226,'Nunc Quisque Ornare LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (54,50,'Aenean Massa Integer Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (115,273,'Ornare Facilisis Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (91,130,'Est Mauris Eu Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (214,100,'Tortor Dictum Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (384,191,'Eleifend Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (208,179,'Sit Amet Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (295,3,'Nibh Aliquam LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (145,145,'Sed PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (193,93,'Ultricies Dignissim Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (338,175,'Libero Et Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (172,74,'Ipsum Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (172,235,'Placerat Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (15,195,'Tempus Lorem Fringilla Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (304,78,'Purus Ac Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (346,77,'A Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (244,82,'Phasellus Dapibus Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (386,177,'Non Leo Vivamus Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (141,98,'Mauris Magna LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (347,213,'Quam Pellentesque Habitant Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (145,241,'In Condimentum Donec Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (63,251,'Netus Et Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (209,223,'Lorem Ut PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (120,220,'Cursus Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (162,17,'Dignissim Tempor Arcu LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (17,187,'Vel Vulputate Eu Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (326,262,'Nonummy Ut Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (162,16,'Dictum Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (287,283,'Cursus Et LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (394,51,'Mauris Vestibulum Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (221,121,'Quam Vel Sapien Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (351,7,'Sapien Nunc Pulvinar Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (90,227,'Vehicula Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (167,253,'Lacinia Orci Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (319,176,'Etiam Bibendum Fermentum Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (318,282,'Erat Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (41,17,'Morbi Metus Vivamus Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (225,220,'Egestas Hendrerit Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (67,34,'Augue Eu Tempor LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (329,259,'Eget Ipsum Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (372,56,'Eget Metus Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (212,20,'Sociosqu Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (156,64,'Fusce Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (7,33,'Tincidunt Orci Quis Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (77,10,'Et Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (306,293,'Cubilia Curae; Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (187,124,'Vivamus Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (44,129,'Penatibus Et Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (375,158,'Aliquam Eros LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (201,71,'At Velit Pellentesque Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (222,290,'Eget Lacus Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (170,87,'Fringilla Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (318,33,'Et Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (205,125,'Diam Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (58,239,'Lorem Sit Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (179,116,'Ante Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (376,93,'Nisl Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (214,172,'Pede Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (301,214,'Arcu Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (352,186,'Ut Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (281,113,'Ante Ipsum Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (147,145,'Euismod Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (168,96,'Duis LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (244,197,'Eu Ultrices Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (113,264,'Orci Associates');

INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (75,271,'Integer In Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (176,73,'Justo Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (205,280,'Risus A Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (182,205,'Nibh Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (350,237,'Dui Cum Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (205,173,'Malesuada Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (163,274,'Consequat Dolor Vitae Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (368,192,'Nunc Sollicitudin Commodo Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (395,140,'Ultricies Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (335,108,'Convallis Erat Eget PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (14,28,'Aliquam Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (301,84,'Ut Nisi A Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (272,5,'Dapibus LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (229,111,'Tortor Nunc Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (85,84,'Hendrerit Neque In Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (162,119,'Velit Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (134,91,'A Facilisis Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (324,98,'Arcu Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (130,109,'Amet Ornare Lectus PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (149,69,'Molestie Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (331,138,'Nisi Cum Sociis Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (287,115,'Aliquam Eros Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (365,97,'Proin LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (304,202,'Pede Ultrices A Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (306,194,'Etiam Gravida Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (202,96,'Enim Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (325,42,'Vel Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (292,235,'Sed Nec Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (164,29,'Gravida Praesent Eu Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (221,14,'Amet Consectetuer Adipiscing Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (258,245,'Dolor Nonummy Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (98,16,'Sit Amet Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (147,130,'Massa Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (226,150,'Pellentesque Eget Dictum Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (26,197,'Ut Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (358,94,'Amet Faucibus LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (203,174,'Lorem Donec Elementum Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (60,264,'Lacinia Vitae Sodales Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (354,232,'Aliquam LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (122,224,'Ante Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (201,130,'Ipsum Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (313,212,'In Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (101,78,'Donec Elementum Lorem Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (9,54,'Sed PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (19,105,'Consectetuer Adipiscing Elit LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (331,101,'Elit PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (355,239,'Consectetuer Adipiscing Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (323,297,'Magna LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (16,22,'Interdum Ligula Eu Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (162,278,'Massa Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (101,229,'Gravida Aliquam Tincidunt PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (157,174,'Mi Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (178,179,'Velit Pellentesque Ultricies LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (34,56,'Fringilla PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (309,139,'Elit Sed Consequat Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (11,300,'Curabitur Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (277,45,'Suscipit Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (15,78,'Ridiculus Mus Proin Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (15,29,'Felis Nulla Tempor Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (25,160,'Tincidunt Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (393,150,'Sed Consequat Auctor PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (46,41,'Sit Amet PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (136,101,'Sem Mollis Dui Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (341,127,'Dapibus Rutrum Justo Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (249,281,'Nec LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (278,47,'Vel Convallis In Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (358,274,'Et Magnis LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (356,124,'Pede Cras Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (95,162,'Eget Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (265,290,'Integer Aliquam Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (91,287,'Lorem Semper Auctor Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (132,238,'Nam Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (265,162,'Egestas Urna LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (361,126,'Ipsum Non Arcu Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (324,264,'Diam Luctus Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (134,112,'Quisque Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (205,105,'Elit Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (261,139,'Donec Luctus Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (287,161,'Quisque Nonummy Ipsum LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (378,104,'Faucibus Ut Nulla Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (172,132,'Lacus Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (94,10,'Nullam Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (117,285,'Luctus Et Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (119,229,'Magna A PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (250,17,'Leo Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (6,225,'Tortor Dictum Eu Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (147,236,'Arcu Curabitur LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (123,49,'Quis Tristique Ac Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (169,220,'Tellus Lorem Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (114,107,'Sed Eu Nibh Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (356,105,'Aenean Massa PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (332,210,'Ut Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (353,38,'Class Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (269,48,'Non Enim Mauris Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (132,278,'Ornare Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (93,234,'Imperdiet Dictum Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (96,103,'Nec Mauris Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (236,40,'Metus Vivamus Euismod Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (341,273,'Montes Nascetur Ridiculus Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (289,137,'Urna Et Incorporated');

INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (144,78,'Turpis Aliquam Adipiscing Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (160,58,'Curabitur Vel Lectus Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (276,156,'Ligula Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (210,170,'Donec Tincidunt Donec Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (256,103,'Elit Pede Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (395,4,'Non Enim Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (124,57,'Sit Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (165,191,'Mauris Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (341,83,'Posuere Enim Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (340,55,'Bibendum Donec Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (126,231,'Sapien Cras Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (390,258,'Porta Elit A Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (339,144,'Magna Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (277,78,'Luctus LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (26,35,'Sed Est Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (338,256,'Per Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (59,59,'Lectus Pede Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (179,55,'Mus Aenean Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (366,152,'Ultricies Ornare Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (381,97,'Mi Enim Condimentum Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (184,64,'Aliquam Ultrices Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (279,271,'Odio Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (387,262,'Sagittis Lobortis Mauris PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (363,262,'Tempor Augue Ac Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (237,154,'Cras Interdum Nunc Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (227,62,'Viverra Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (152,238,'Montes Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (252,144,'Vel Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (206,142,'Molestie Tortor Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (99,34,'Non Bibendum Sed Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (168,216,'A LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (171,154,'Donec Nibh Quisque Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (136,144,'Ullamcorper Duis Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (79,218,'Eget Magna Suspendisse Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (384,145,'Molestie Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (177,143,'Erat Etiam Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (215,135,'Dolor Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (91,55,'Nullam Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (306,54,'Donec Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (191,144,'Aliquet Odio Etiam Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (382,103,'Gravida Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (266,152,'Aliquam Gravida Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (312,158,'Vulputate Dui Nec Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (281,298,'Lectus Nullam Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (349,234,'Praesent Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (321,117,'Laoreet Ipsum Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (261,285,'Ipsum Porta Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (228,198,'Pharetra Quisque Ac Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (339,223,'A Dui LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (303,261,'Ac Eleifend Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (33,138,'Ac Facilisis PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (309,299,'Et Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (149,232,'Sit Amet Nulla LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (270,105,'Morbi Quis Urna Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (183,275,'Et Magnis Dis PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (228,158,'Congue Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (54,50,'A Purus Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (110,116,'Et Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (31,92,'Vivamus Nibh Dolor Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (370,277,'Eu Euismod Ac PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (47,245,'Mauris Suspendisse Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (72,236,'Penatibus Et Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (80,284,'Congue Elit Sed Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (205,133,'Euismod Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (187,177,'Quam Quis Diam Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (333,161,'Hendrerit Neque In Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (108,137,'Lorem Sit Amet Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (385,202,'Sodales Purus Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (102,33,'Quis Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (46,66,'Libero Proin Sed Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (161,44,'Consequat Lectus Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (373,144,'Non Dapibus Rutrum Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (373,66,'Nec LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (54,175,'Malesuada LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (383,53,'Cras Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (250,105,'Tempus Eu Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (289,132,'Facilisi Sed Neque Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (329,32,'At Velit Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (119,164,'Orci In Consequat LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (194,242,'Quisque Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (380,93,'Lorem Semper Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (19,193,'Luctus Ipsum Leo Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (119,2,'Ipsum Leo Elementum Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (288,54,'Velit Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (187,168,'Quisque Tincidunt Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (19,197,'Integer Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (102,34,'Fusce LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (279,93,'Est Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (329,61,'Semper Erat In Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (395,241,'Non Cursus Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (186,261,'Tincidunt LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (390,184,'Ligula Nullam Enim LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (14,67,'Cum LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (397,26,'Libero At PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (375,127,'Ipsum Ac Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (321,14,'Cras Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (55,216,'Dis Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (350,258,'Pharetra LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (306,296,'Ipsum Non Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (249,150,'Nunc Associates');

INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (325,104,'Interdum LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (69,191,'Orci Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (300,107,'Egestas Aliquam Fringilla Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (167,196,'Imperdiet LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (19,116,'Lacus Nulla Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (266,232,'Enim Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (100,11,'Velit Sed Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (90,247,'Sed Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (21,41,'Eu Neque LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (22,218,'Sed Eu Nibh Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (210,115,'Nec Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (237,13,'Sit Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (357,113,'Eu Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (248,99,'Enim Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (72,134,'Proin LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (129,76,'Amet Lorem Semper Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (140,1,'Dolor Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (221,180,'Aliquam Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (83,104,'Nunc Est LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (336,35,'Montes Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (68,82,'Sem Ut LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (273,6,'Egestas A Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (130,130,'Tortor Nibh Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (180,34,'Congue Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (129,183,'Senectus Et Netus Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (202,42,'Porttitor Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (340,30,'Libero LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (194,47,'Aliquam Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (90,69,'Mauris Id Sapien Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (376,196,'Amet Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (55,15,'Dictum Placerat Augue Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (34,272,'Ac Nulla In Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (201,101,'Orci Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (214,178,'Lectus Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (181,122,'Tellus Aenean Egestas Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (370,179,'Fermentum Risus PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (386,17,'Proin Dolor Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (109,118,'Ligula Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (367,143,'Aliquam Erat Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (242,145,'Dictum Phasellus In Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (321,197,'Non Dui Nec LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (357,193,'Nunc Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (311,78,'Turpis Nec Mauris LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (26,50,'Vitae Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (23,121,'Donec At Arcu Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (97,3,'Ultricies LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (152,99,'Et Netus Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (173,205,'Sed Sapien Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (32,20,'Magnis Dis Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (279,175,'Nec Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (62,257,'Cras Convallis Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (349,137,'Ac Nulla In Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (10,23,'Curabitur Consequat Lectus Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (23,22,'Donec Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (224,181,'Imperdiet Nec Leo LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (38,167,'Vitae Mauris LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (269,81,'Proin Ultrices Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (240,148,'Fermentum Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (314,14,'Quam Pellentesque Habitant Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (94,74,'Tempus Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (108,179,'Mi LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (206,270,'Enim Mauris Quis Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (315,133,'Mus Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (85,282,'Dictum Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (313,134,'Enim Consequat Purus Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (390,41,'Lacus Nulla Tincidunt Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (251,74,'Morbi Quis Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (132,212,'Eleifend Egestas Sed Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (362,28,'In Faucibus Orci Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (185,116,'Ullamcorper Magna Sed Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (262,146,'Laoreet Lectus Quis Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (192,266,'Faucibus Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (301,39,'Orci Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (304,93,'Volutpat Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (357,137,'Nec Tempus Mauris Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (180,93,'Molestie LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (292,87,'Eleifend Nunc Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (324,273,'At Fringilla Purus Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (5,91,'Facilisis Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (336,216,'At Sem Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (165,237,'Quam Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (250,191,'Fermentum Vel LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (18,229,'Magna Lorem Ipsum Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (263,151,'Dolor Sit Amet PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (176,166,'Phasellus Ornare Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (231,206,'Sed Hendrerit Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (181,221,'Vulputate Risus PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (148,235,'Urna Nullam Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (161,113,'Arcu Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (155,95,'Ut Aliquam Iaculis Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (213,125,'Eleifend Vitae Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (156,166,'Vel Est Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (17,75,'Tellus Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (315,287,'Euismod Et Commodo LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (22,35,'Justo Eu Arcu Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (352,40,'Aliquam Erat Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (210,131,'Pellentesque Ut Ipsum Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (306,292,'Turpis Vitae Purus Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (96,98,'Eget Tincidunt PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (381,180,'Integer Aliquam Adipiscing Consulting');

INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (340,179,'Etiam Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (67,248,'Ipsum Primis Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (297,115,'Nibh Vulputate PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (67,53,'Blandit LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (35,154,'Dis Parturient Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (335,252,'Fusce Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (373,172,'Rutrum Justo Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (162,293,'Vitae Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (296,227,'Ornare Facilisis Eget Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (240,6,'Natoque Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (82,76,'Adipiscing Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (36,193,'Cursus Luctus Ipsum Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (293,183,'Auctor Non PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (187,135,'Aptent Taciti Foundation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (332,99,'Arcu Et Pede Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (142,140,'Lectus LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (318,270,'Nunc LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (227,235,'Malesuada Malesuada Integer LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (102,49,'Vehicula Pellentesque Tincidunt Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (133,118,'Nullam Velit Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (340,294,'Ultrices Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (261,89,'Vehicula Pellentesque Tincidunt Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (14,49,'Turpis Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (372,154,'Urna Suscipit Nonummy Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (78,27,'Faucibus Lectus Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (209,275,'Odio Vel LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (26,226,'Facilisis Non Bibendum LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (9,47,'Malesuada Ut LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (206,198,'Aliquet Metus Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (255,229,'Et Magnis Dis Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (16,204,'Magnis Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (108,196,'Id Libero Donec LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (79,275,'Orci PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (143,251,'Non Industries');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (20,31,'A Magna Lorem Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (309,155,'Non Magna Nam Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (310,142,'Donec Egestas Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (232,124,'Vulputate Lacus Cras Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (275,53,'Aliquam Erat Volutpat PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (75,273,'Nisi Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (139,298,'Lobortis Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (100,191,'Lectus A Sollicitudin LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (212,99,'Pellentesque Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (51,114,'Est Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (312,232,'Arcu Curabitur LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (6,145,'Ridiculus Mus Proin Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (223,47,'At Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (151,59,'Imperdiet Incorporated');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (254,126,'Placerat Augue LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (85,168,'Gravida Sagittis Duis Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (164,228,'Donec PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (42,196,'Nullam Scelerisque Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (91,182,'Sociis Natoque Penatibus Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (277,141,'Leo Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (100,117,'In Sodales Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (361,187,'Duis Ac PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (81,60,'Elit PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (55,177,'Nullam PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (381,239,'Maecenas LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (362,65,'Convallis Dolor Quisque LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (361,51,'Ultricies Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (164,232,'Ut Dolor Dapibus Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (280,153,'Enim Suspendisse Aliquet Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (151,58,'Aenean Sed Pede Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (87,203,'Semper Et Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (78,222,'Dis Parturient Montes Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (44,175,'Nisi Dictum Augue Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (65,77,'Ut Eros Non Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (228,162,'Ultrices Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (236,203,'Consequat Dolor PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (84,263,'Sed Et LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (116,44,'Lorem Ipsum Company');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (282,14,'Sem Egestas Blandit Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (351,193,'Vitae Mauris Sit LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (168,160,'Et Eros Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (265,108,'Erat Vivamus LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (30,79,'Dui Cras Pellentesque Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (188,100,'Mauris Institute');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (90,17,'Facilisis LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (206,15,'Vitae Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (396,55,'Dui Fusce Diam Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (78,195,'Dui Fusce Aliquam LLP');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (20,95,'Sit Amet Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (329,205,'Consequat Enim Diam Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (218,223,'Praesent Eu Dui Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (279,80,'Ridiculus Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (294,241,'Mauris Morbi PC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (36,260,'Ligula Elit Corp.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (166,269,'Lorem Corporation');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (90,74,'Lorem Eu Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (213,148,'Etiam Gravida Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (242,228,'Dictum Consulting');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (3,196,'Pede Ltd');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (75,87,'Nulla Magna Malesuada LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (194,226,'Imperdiet LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (5,190,'Libero Nec LLC');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (40,283,'Eget Venenatis A Inc.');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (18,119,'Consequat Dolor Limited');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (284,196,'Primis In Faucibus Associates');
INSERT INTO Obchod (obchodID,lokalitaID,nazev) VALUES (114,44,'At Libero PC');

