INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nam Tempor Diam Corp.',39);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dictum Phasellus Incorporated',60);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ut Incorporated',96);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Metus Vivamus Institute',91);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vulputate Risus A Corporation',91);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sociis Natoque Foundation',30);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Eu Eros Nam Inc.',47);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ac Eleifend Foundation',45);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Justo Corporation',15);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Magna Sed Dui Company',27);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Auctor Odio A PC',65);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vitae Sodales Institute',17);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nec Euismod Foundation',100);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Consequat Purus LLC',19);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Et Magnis Dis Associates',19);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Rhoncus Consulting',47);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sem Egestas Incorporated',54);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sit Amet LLP',13);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Et Arcu Imperdiet Corp.',58);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nibh Sit Amet LLC',22);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Fermentum Metus Aenean Industries',47);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Quis Foundation',13);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ut Nulla Cras LLP',18);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dis Parturient Montes Institute',69);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Rhoncus Proin Foundation',77);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Id Libero PC',69);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Quis Massa Mauris Associates',4);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Faucibus Orci Ltd',30);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sed Libero Incorporated',100);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Feugiat Placerat Velit Corporation',98);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Fringilla Donec Feugiat Corporation',26);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Libero Donec Associates',20);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Elit Pretium Et Inc.',25);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Urna Ut Tincidunt Consulting',20);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dolor PC',15);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Metus Vitae Velit Limited',42);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Phasellus Fermentum Associates',16);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Non Luctus Sit PC',71);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Eleifend LLC',97);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nunc Quis LLP',98);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nunc Ut Institute',81);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Venenatis LLC',51);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Lectus Convallis Est Incorporated',79);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Pede Praesent Eu Company',15);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nunc In Ltd',51);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dolor Sit Foundation',88);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Rutrum Corporation',90);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mauris Non Dui Foundation',37);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Arcu Sed Associates',49);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Facilisis Vitae Inc.',55);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Proin Eget Odio Institute',16);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Iaculis Odio Nam Corp.',76);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Praesent Eu Industries',66);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Auctor Ullamcorper Inc.',13);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ornare Lectus Incorporated',17);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mauris Blandit Mattis Inc.',62);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ut Erat Sed Associates',11);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nec Cursus Inc.',28);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Eget Dictum Placerat Limited',70);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Proin Ultrices Duis Institute',21);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Adipiscing Lobortis Incorporated',26);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('A Corporation',38);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Lobortis Class Incorporated',72);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Imperdiet Foundation',78);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Risus Duis A LLC',4);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Netus Company',70);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Elementum At Egestas Consulting',29);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Facilisis Ltd',62);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Posuere Vulputate Limited',59);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Libero LLC',20);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Proin Incorporated',45);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Fermentum Foundation',26);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Faucibus Orci Luctus Consulting',56);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mauris Ut Quam Consulting',95);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ultrices Company',18);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Egestas Aliquam Company',100);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Erat Foundation',67);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dictum Foundation',62);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Tincidunt Tempus Risus Inc.',72);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Pulvinar Associates',83);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vitae Erat Foundation',1);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Risus Consulting',58);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mi Fringilla Mi Ltd',26);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Cum Sociis Natoque Corp.',27);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Scelerisque Scelerisque Dui Associates',43);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Donec Company',76);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Suspendisse Sed Incorporated',46);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Purus Duis Corp.',16);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sagittis Foundation',77);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nulla Eu Institute',13);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Massa Quisque Associates',51);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mauris Associates',48);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Magna Lorem Inc.',82);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Elementum Purus Incorporated',42);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ut Foundation',57);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mi Consulting',26);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Magna Malesuada Vel Associates',92);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aenean Egestas Ltd',74);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Auctor Velit Eget Inc.',6);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sed Facilisis PC',5);

INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mauris Company',60);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sapien LLC',60);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('At Risus Institute',3);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Diam Vel Inc.',54);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sit Amet Ltd',48);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Lacinia Institute',77);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dolor Egestas Ltd',79);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dis Parturient Montes Foundation',46);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Facilisis Vitae Orci Corporation',85);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Tempor Lorem Eget Associates',20);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Lacinia LLP',64);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Lacus Mauris Non Limited',5);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Erat Limited',39);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dui Suspendisse Ac LLC',99);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Non Lobortis Industries',99);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Consectetuer Mauris LLC',24);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Molestie Arcu Sed Corporation',64);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aliquam Industries',81);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aliquam Inc.',62);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Pede Limited',46);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dignissim Industries',83);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vitae Nibh Donec Incorporated',54);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dapibus Industries',85);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Scelerisque Scelerisque LLP',58);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Elit Etiam LLC',57);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Enim LLC',24);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nec Imperdiet Nec Industries',3);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vel Quam Dignissim Corporation',91);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Porttitor Vulputate Posuere Corporation',33);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Diam Duis Mi Foundation',69);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Habitant Morbi Inc.',84);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Velit PC',34);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Duis A Mi Limited',70);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('In Nec Orci Consulting',83);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Convallis Convallis Dolor Incorporated',8);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Natoque Foundation',55);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Lectus Ante Dictum Corp.',7);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mus Proin Vel Associates',46);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dis Parturient Montes Institute',1);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sed Orci Inc.',33);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mauris Corp.',41);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aenean LLC',46);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vulputate Industries',16);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aliquet Vel LLC',51);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ut Quam Vel Inc.',7);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Purus Ac PC',11);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ut Erat Limited',47);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Est Nunc Laoreet PC',68);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mauris Aliquam Inc.',60);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Bibendum Corp.',69);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Turpis Egestas Aliquam PC',36);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('At Augue Corporation',35);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Egestas Blandit Corp.',99);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Non Associates',67);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sapien Industries',31);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Leo Cras Vehicula LLP',83);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Congue A Aliquet PC',52);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Amet Diam Corp.',1);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Neque Nullam Nisl Inc.',62);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nunc Pulvinar Foundation',86);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Arcu Vestibulum LLC',22);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Lectus Pede Limited',72);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sed Corp.',61);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Non Massa PC',61);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nunc Sollicitudin Commodo Industries',8);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Et Limited',33);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Donec Limited',62);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Curabitur Dictum Industries',85);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ac Tellus Corp.',14);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Fermentum Fermentum Arcu Foundation',60);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Velit Egestas Lacinia Industries',3);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Donec Elementum Lorem LLP',74);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nunc Nulla Vulputate Foundation',9);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Interdum Curabitur Corporation',46);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Risus Duis A LLP',37);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Orci LLP',80);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Semper Industries',80);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Tempor Augue Associates',99);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Diam Pellentesque Associates',64);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Quisque Libero Lacus Corporation',67);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Et Industries',96);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nam Tempor Diam Company',49);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nullam Inc.',86);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nulla PC',10);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dui Nec Urna PC',15);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Amet Corporation',30);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nisi Institute',64);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Penatibus Et Magnis Corporation',4);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sed Libero Industries',82);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Non Incorporated',85);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aliquam Eros Corporation',98);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nunc Pulvinar Arcu Incorporated',90);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nibh Vulputate Mauris Ltd',79);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Porttitor Company',23);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ac Eleifend Ltd',48);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ornare Foundation',28);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Elit Fermentum Limited',40);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vitae Posuere At Consulting',38);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dui Foundation',13);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nonummy Company',7);

INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Porta Elit Ltd',56);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nulla In Tincidunt Institute',20);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mi Felis Inc.',87);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Fringilla Est Mauris Industries',90);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nec Urna Inc.',69);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Eleifend Limited',2);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sem Ut Company',95);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Phasellus Ornare Institute',4);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Urna Nullam Lobortis Institute',27);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ornare Facilisis PC',49);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Eu Ligula LLP',71);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Venenatis Lacus Etiam Ltd',79);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('In At Pede Consulting',77);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vestibulum Neque Sed Associates',45);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dolor Sit Inc.',19);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nec Quam Curabitur Ltd',36);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Molestie Consulting',94);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Cursus Ltd',24);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Etiam Ltd',47);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Lorem Company',74);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Semper Cursus Associates',63);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vel LLC',70);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Pretium Neque Morbi Company',3);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Pellentesque Ut Ipsum LLP',70);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aliquam Arcu Institute',5);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vehicula Pellentesque Tincidunt PC',27);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dolor Fusce LLP',66);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Amet Nulla Corporation',29);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Eu Tellus Phasellus LLP',41);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Donec Sollicitudin Inc.',77);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Id Nunc Limited',69);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Tellus Foundation',42);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Orci Ut Sagittis Incorporated',13);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Turpis Nulla Aliquet Corporation',35);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Tristique Senectus Limited',28);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ornare Sagittis Felis Ltd',63);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ante Bibendum Associates',90);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Erat Semper Institute',50);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Duis Limited',38);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Posuere Vulputate Foundation',43);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Commodo Institute',45);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Natoque Penatibus Et Consulting',46);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Orci Sem Eget Limited',78);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aliquet Proin Velit Consulting',86);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Luctus Aliquet Consulting',49);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Amet Consectetuer Corporation',12);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ultricies Foundation',57);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Metus Aliquam Inc.',3);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ante Iaculis Associates',94);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vehicula Risus Nulla Institute',61);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aliquam Erat Industries',35);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ac Fermentum Vel Consulting',88);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Rhoncus Nullam Velit Corporation',44);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Cras Sed LLP',58);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Lorem Vitae Foundation',35);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Non Limited',89);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mollis Incorporated',76);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Risus A Ultricies Foundation',26);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Gravida Corp.',24);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Morbi Neque Tellus Corp.',40);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Integer Eu Lacus Corp.',79);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Scelerisque LLC',83);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Proin Company',57);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nunc Id Corp.',36);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Et Consulting',33);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ut LLP',27);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Egestas Duis Inc.',60);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nec Corporation',100);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nulla Semper Tellus LLP',69);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Leo LLC',3);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ad Litora Corporation',50);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Curabitur Ltd',47);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ipsum Suspendisse Limited',72);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dui Nec Urna Foundation',53);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('In Ltd',7);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aliquet Ltd',52);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Tempor Associates',93);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ut Cursus LLC',80);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ut Cursus Luctus Company',29);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Lorem Ipsum Sodales PC',50);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vitae Corp.',44);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Curabitur Corporation',26);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Tristique Corp.',93);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Praesent Eu Industries',75);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sit Amet Massa PC',85);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dictum Placerat Augue Inc.',47);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Gravida Molestie Foundation',47);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Tristique Ac Foundation',77);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aenean Euismod Mauris Incorporated',29);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Quis Tristique Ac Incorporated',49);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Odio Semper Cursus Industries',70);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Tellus Eu Corporation',16);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Eu Tellus Phasellus Foundation',43);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aliquet Sem Incorporated',23);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Magnis LLP',77);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Enim Inc.',5);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Donec LLP',46);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ante Vivamus Non Ltd',7);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Id Blandit Inc.',84);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Molestie Sed Id Company',3);

INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aptent LLP',30);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sed Institute',48);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nunc Id Enim LLC',19);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Lacus Corp.',81);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Egestas Ligula Corporation',44);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Magna A Neque Company',1);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Est Congue A Ltd',20);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Netus Et Malesuada Inc.',3);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Varius Consulting',16);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Rhoncus Proin LLP',4);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Gravida PC',72);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Et Inc.',35);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Duis Associates',69);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Risus Institute',65);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vel Foundation',36);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Non Enim Mauris Inc.',80);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Amet Risus Donec Inc.',66);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vehicula Pellentesque Incorporated',8);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Volutpat Ornare Facilisis Institute',74);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Eget Incorporated',39);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Non Consulting',53);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Placerat Velit LLP',9);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Elit Ltd',68);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Semper Pretium Neque Ltd',77);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sed Hendrerit Incorporated',70);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Etiam Bibendum Fermentum Industries',44);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Aliquam Company',47);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Consequat Limited',91);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Fringilla Ornare LLP',1);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Amet Lorem Semper Company',53);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Magna Consulting',5);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mi Enim Condimentum LLC',91);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Non Massa LLP',73);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ante Lectus Ltd',8);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sed Nulla Consulting',57);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Donec Egestas LLC',55);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Feugiat Associates',21);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Cras Vehicula Incorporated',92);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('In Lobortis Tellus Corporation',61);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nisi Dictum Ltd',37);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Est Ac Mattis LLC',60);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('At Company',48);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Pede Ac PC',71);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Cubilia Curae; Donec Company',62);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Amet Risus Incorporated',59);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ligula Consectetuer Rhoncus PC',81);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sapien LLP',95);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Accumsan Convallis Ante LLC',70);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Egestas Lacinia Associates',86);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Est Incorporated',82);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Dui In Sodales Ltd',89);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Egestas Lacinia Limited',59);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nam Inc.',36);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Curabitur Vel Corp.',76);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Integer PC',17);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Risus Foundation',4);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Elit Sed Ltd',47);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ut Quam Vel Institute',62);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Semper Egestas LLP',21);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Interdum Associates',6);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Id Foundation',8);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nisi Industries',92);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Quis Accumsan PC',28);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Blandit Congue In LLP',50);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('In Condimentum Donec Consulting',64);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vel Convallis In Foundation',79);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vel Est Corporation',8);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Auctor Incorporated',77);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sodales Company',8);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nibh Company',82);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Donec Egestas Duis Foundation',51);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Arcu Industries',50);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Magna LLC',82);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sed Libero Proin Foundation',75);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Molestie In Inc.',58);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Mauris Blandit Mattis LLC',55);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Lorem Institute',53);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('In Cursus Company',67);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Eu Nulla Corporation',93);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nunc Mauris Sapien Company',56);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Orci Corp.',86);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Enim Nisl Elementum Limited',34);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Interdum Sed Corporation',51);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Enim Curabitur Massa LLP',97);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Adipiscing Lacus Ut Foundation',91);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Convallis Inc.',49);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Curae; Donec Tincidunt Ltd',23);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Nunc Id Company',49);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sem Nulla Interdum Industries',32);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Quis Pede Suspendisse LLP',66);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Purus Accumsan Foundation',33);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Vitae Erat Vel Corporation',92);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Sed LLC',49);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Leo Vivamus Nibh Ltd',47);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Molestie Arcu Sed Inc.',74);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Tempor Bibendum Institute',76);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Erat Associates',94);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Ipsum Non Arcu Industries',59);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Malesuada Vel Company',84);
INSERT INTO Oddeleni (nazev,orgJednotkaId) VALUES ('Pellentesque Eget Inc.',20);

