INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1219,'Ligula Consulting',355,328);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1898,'Vivamus Consulting',178,164);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1829,'Vel Convallis In Industries',461,114);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1129,'Nonummy Inc.',30,721);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1748,'Magna Consulting',15,296);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1788,'Quam Curabitur Consulting',108,316);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1442,'Urna LLP',399,382);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1089,'Nunc Est Mollis Consulting',393,219);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1813,'Nunc Sed Libero Company',119,780);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1963,'Lectus Quis Associates',294,200);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1838,'Tellus Lorem Associates',318,177);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1819,'Sapien PC',201,823);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1315,'Vitae Associates',477,447);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1239,'Elementum Associates',396,755);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1115,'Sed Sapien Nunc Limited',465,514);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1263,'Dictum PC',137,821);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1340,'Turpis Vitae Purus Foundation',195,80);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1677,'Gravida Nunc Sed Associates',267,631);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1031,'Aliquam Ornare Company',134,699);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1539,'Lectus Consulting',27,437);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1252,'Ut Nec Incorporated',404,725);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1811,'Justo Proin Non Industries',467,368);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1582,'Et Netus LLP',111,635);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1139,'Donec Tincidunt PC',295,536);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1588,'Tincidunt Donec Vitae LLP',401,557);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1130,'Primis In Consulting',256,299);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1074,'Scelerisque Neque Limited',117,617);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1846,'Ante Vivamus Foundation',445,187);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1543,'Inceptos Hymenaeos Company',234,783);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1330,'Ridiculus Industries',216,483);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1781,'Mauris Company',369,195);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1989,'Sapien Nunc Pulvinar LLP',474,184);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1554,'Mus Inc.',211,985);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1724,'Cras Pellentesque Sed Company',209,908);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1382,'Libero Donec Associates',134,34);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1746,'Quis Diam Luctus Associates',316,19);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1247,'Cursus Ltd',14,798);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1374,'Egestas Sed Limited',34,321);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1452,'Pede Suspendisse Dui Corp.',288,266);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1433,'Duis Corporation',81,474);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1464,'Donec Est Corporation',233,458);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1173,'Arcu Curabitur Associates',325,641);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1667,'Vitae Corporation',462,569);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1812,'Nunc Corporation',37,194);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1332,'Ut LLP',50,344);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1800,'Sed Molestie Institute',397,215);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1290,'Penatibus Incorporated',1,473);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1848,'Sit Amet Risus LLP',456,933);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1194,'Mauris LLC',125,154);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1258,'Odio A Ltd',356,143);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1631,'Enim Mi Ltd',62,976);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1475,'Dolor Sit Amet Company',178,341);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1176,'Tellus Incorporated',500,401);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1473,'Sit Amet Risus LLC',12,775);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1854,'A Auctor Non Foundation',179,97);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1363,'Ut Tincidunt Foundation',366,109);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1200,'Enim Ltd',37,932);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1091,'Sollicitudin Consulting',180,446);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1574,'Eget Foundation',100,737);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1789,'Sodales Elit Erat Associates',238,232);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1963,'Amet Limited',454,941);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1344,'Mollis Non LLP',387,616);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1389,'Dui Fusce Diam Corp.',284,87);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1772,'Id Blandit At Foundation',160,335);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1558,'At Iaculis Quis Ltd',87,262);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1457,'Convallis Consulting',374,993);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1166,'Dolor Dapibus Associates',88,698);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1242,'Vitae Associates',418,907);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1841,'Donec Ltd',310,521);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1554,'Orci Inc.',407,401);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1641,'At Ltd',137,746);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1772,'Ligula Institute',207,703);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1550,'Vivamus Nibh Dolor LLP',382,12);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1360,'In Aliquet Lobortis Institute',163,40);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1003,'In Tempus Eu Incorporated',342,293);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1133,'A Foundation',436,298);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1807,'Suspendisse Associates',447,53);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1462,'Cursus Integer Foundation',399,342);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1807,'Consequat LLC',153,328);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1304,'Interdum Industries',418,283);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1701,'Mauris Erat Foundation',189,950);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1699,'Vitae Erat Vel Inc.',143,705);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1731,'Lorem Auctor Quis Industries',341,310);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1786,'Justo Sit LLP',291,524);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1360,'Ornare Company',384,419);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1239,'Ipsum Ac Mi Industries',77,464);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1894,'Nec Enim Limited',54,198);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1538,'Non Lacinia LLP',444,621);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1455,'Ultrices Iaculis Industries',125,136);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1288,'Odio Corporation',168,63);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1699,'Curabitur LLC',222,631);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1916,'Adipiscing Enim Ltd',292,983);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1252,'Sed Orci Lobortis Consulting',258,40);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1596,'Porttitor Company',68,563);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1330,'Donec Associates',73,36);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1157,'Vel Inc.',447,679);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1560,'Vehicula Aliquet Corporation',234,823);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1457,'Quisque Tincidunt Pede Ltd',51,60);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1568,'Faucibus LLC',305,891);
INSERT INTO OrgJednotka (id,nazev,adresaID,zamestnanecID) VALUES (1441,'Auctor Odio Company',219,586);

